# Generated by Django 3.2.12 on 2022-03-05 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("sub_name", models.CharField(default="", max_length=300)),
                (
                    "type",
                    models.CharField(
                        choices=[("NEW_BOOK", "새 책"), ("USED_BOOK", "중고 책"), ("E_BOOKS", "E-Book")],
                        default="NEW_BOOK",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(null=True)),
                ("price", models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ("sale_price", models.DecimalField(decimal_places=0, max_digits=5, null=True)),
                ("purchased_at", models.DateField(null=True)),
                ("published_at", models.DateField(null=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="bms.author")),
                ("tags", models.ManyToManyField(to="bms.Tag")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
